import type { PickierConfig } from './types'
import { loadConfig } from 'bunfig'

export const defaultConfig: PickierConfig = {
  ignores: [
    '**/node_modules/**',
    '**/.pnpm/**',
    '**/.yarn/**',
    '**/dist/**',
    '**/build/**',
    '**/out/**',
    '**/.output/**',
    '**/.next/**',
    '**/.nuxt/**',
    '**/.vite/**',
    '**/.turbo/**',
    '**/.cache/**',
    '**/coverage/**',
    '**/vendor/**',
    '**/tmp/**',
    '**/.git/**',
    '**/.idea/**',
    '**/.vscode/**',
    '**/*.test.ts',
    '**/*.spec.ts',
  ],
  lint: {
    extensions: ['ts', 'js', 'html', 'css', 'json', 'jsonc', 'md', 'yaml', 'yml', 'stx'],
    reporter: 'stylish',
    cache: false,
    maxWarnings: -1,
  },
  format: {
    extensions: ['ts', 'js', 'html', 'css', 'json', 'jsonc', 'md', 'yaml', 'yml', 'stx'],
    trimTrailingWhitespace: true,
    maxConsecutiveBlankLines: 1,
    finalNewline: 'one',
    indent: 2,
    indentStyle: 'spaces',
    quotes: 'single',
    semi: false,
  },
  rules: {
    noDebugger: 'error',
    noConsole: 'warn',
  },
  pluginRules: {
    'style/brace-style': 'warn',
    'style/curly': 'off',
    'style/if-newline': 'off',
    'style/max-statements-per-line': 'warn',
    'pickier/import-dedupe': 'warn',
    'pickier/no-import-node-modules-by-path': 'error',
    'pickier/no-import-dist': 'error',
    'pickier/prefer-const': 'error',
    'pickier/prefer-template': 'warn',
    'pickier/no-unused-vars': 'error',
    'regexp/no-unused-capturing-group': 'error',
    'regexp/no-super-linear-backtracking': 'error',
    'regexp/no-useless-lazy': 'error',
    'ts/no-top-level-await': 'error',
    // Markdown rules
    'markdown/heading-increment': 'error',
    'markdown/heading-style': 'warn',
    'markdown/no-missing-space-atx': 'error',
    'markdown/no-multiple-space-atx': 'error',
    'markdown/no-missing-space-closed-atx': 'error',
    'markdown/no-multiple-space-closed-atx': 'error',
    'markdown/blanks-around-headings': 'warn',
    'markdown/heading-start-left': 'error',
    'markdown/no-duplicate-heading': 'warn',
    'markdown/single-title': 'error',
    'markdown/no-trailing-punctuation': 'warn',
    'markdown/ul-style': 'warn',
    'markdown/list-indent': 'error',
    'markdown/ul-indent': 'error',
    'markdown/ol-prefix': 'warn',
    'markdown/list-marker-space': 'error',
    'markdown/blanks-around-lists': 'warn',
    'markdown/no-trailing-spaces': 'error',
    'markdown/no-hard-tabs': 'error',
    'markdown/no-multiple-blanks': 'warn',
    'markdown/no-multiple-space-blockquote': 'error',
    'markdown/no-blanks-blockquote': 'warn',
    'markdown/blanks-around-fences': 'warn',
    'markdown/single-trailing-newline': 'error',
    'markdown/blanks-around-tables': 'warn',
    'markdown/no-reversed-links': 'error',
    'markdown/no-bare-urls': 'warn',
    'markdown/no-space-in-links': 'error',
    'markdown/no-empty-links': 'error',
    'markdown/link-fragments': 'warn',
    'markdown/reference-links-images': 'warn',
    'markdown/link-image-reference-definitions': 'warn',
    'markdown/link-image-style': 'warn',
    'markdown/descriptive-link-text': 'warn',
    'markdown/line-length': 'off',
    'markdown/commands-show-output': 'warn',
    'markdown/fenced-code-language': 'warn',
    'markdown/code-block-style': 'warn',
    'markdown/code-fence-style': 'warn',
    'markdown/no-emphasis-as-heading': 'warn',
    'markdown/no-space-in-emphasis': 'error',
    'markdown/no-space-in-code': 'error',
    'markdown/emphasis-style': 'warn',
    'markdown/strong-style': 'warn',
    'markdown/no-inline-html': 'warn',
    'markdown/hr-style': 'warn',
    'markdown/first-line-heading': 'off',
    'markdown/required-headings': 'off',
    'markdown/proper-names': 'off',
    'markdown/no-alt-text': 'warn',
    'markdown/table-pipe-style': 'warn',
    'markdown/table-column-count': 'error',
    'markdown/table-column-style': 'warn',
  },
  verbose: true,
}

// eslint-disable-next-line antfu/no-top-level-await
export const config: PickierConfig = await loadConfig({
  name: 'pickier',
  defaultConfig,
})
