import type { PickierConfig } from './types'
import { loadConfig } from 'bunfig'

export const defaultConfig: PickierConfig = {
  ignores: [
    '**/node_modules/**',
    '**/.pnpm/**',
    '**/.yarn/**',
    '**/dist/**',
    '**/build/**',
    '**/out/**',
    '**/.output/**',
    '**/.next/**',
    '**/.nuxt/**',
    '**/.vite/**',
    '**/.turbo/**',
    '**/.cache/**',
    '**/coverage/**',
    '**/vendor/**',
    '**/pantry/**',
    '**/tmp/**',
    '**/.git/**',
    '**/.idea/**',
    '**/.vscode/**',
    '**/.zed/**',
    '**/.cursor/**',
    '**/.claude/**',
    '**/.github/**',
    '**/*.test.ts',
    '**/*.spec.ts',
  ],
  lint: {
    extensions: ['ts', 'js', 'html', 'css', 'json', 'jsonc', 'md', 'yaml', 'yml', 'stx', 'lock'],
    reporter: 'stylish',
    cache: false,
    maxWarnings: -1,
  },
  format: {
    extensions: ['ts', 'js', 'html', 'css', 'json', 'jsonc', 'md', 'yaml', 'yml', 'stx'],
    trimTrailingWhitespace: true,
    maxConsecutiveBlankLines: 1,
    finalNewline: 'one',
    indent: 2,
    indentStyle: 'spaces',
    quotes: 'single',
    semi: false,
  },
  rules: {
    noDebugger: 'error',
    noConsole: 'warn',
  },
  pluginRules: {
    'style/brace-style': 'warn',
    'style/curly': 'off',
    'style/if-newline': 'off',
    'style/max-statements-per-line': 'warn',
    'pickier/import-dedupe': 'warn',
    'pickier/no-import-node-modules-by-path': 'error',
    'pickier/no-import-dist': 'error',
    'pickier/prefer-const': 'error',
    'pickier/prefer-template': 'warn',
    'pickier/no-unused-vars': 'error',
    'regexp/no-unused-capturing-group': 'error',
    'regexp/no-super-linear-backtracking': 'error',
    'regexp/no-useless-lazy': 'error',
    'ts/no-top-level-await': 'error',
    'ts/member-delimiter-style': 'off',
    'ts/type-annotation-spacing': 'off',
    // Style formatting rules
    'style/comma-dangle': 'off',
    'style/keyword-spacing': 'off',
    'style/arrow-spacing': 'off',
    'style/space-infix-ops': 'off',
    'style/object-curly-spacing': 'off',
    'style/spaced-comment': 'off',
    'style/block-spacing': 'off',
    'style/space-before-blocks': 'off',
    'style/comma-spacing': 'off',
    'style/semi-spacing': 'off',
    'style/rest-spread-spacing': 'off',
    'style/key-spacing': 'off',
    'style/computed-property-spacing': 'off',
    'style/array-bracket-spacing': 'off',
    'style/space-in-parens': 'off',
    'style/template-curly-spacing': 'off',
    'style/space-unary-ops': 'off',
    'style/switch-colon-spacing': 'off',
    'style/arrow-parens': 'off',
    'style/space-before-function-paren': 'off',
    'style/quote-props': 'off',
    'style/no-floating-decimal': 'off',
    'style/new-parens': 'off',
    'style/no-extra-parens': 'off',
    'style/wrap-iife': 'off',
    'style/comma-style': 'off',
    'style/dot-location': 'off',
    'style/operator-linebreak': 'off',
    'style/multiline-ternary': 'off',
    'style/padded-blocks': 'off',
    'style/lines-between-class-members': 'off',
    'style/no-tabs': 'off',
    'style/no-mixed-spaces-and-tabs': 'off',
    'style/generator-star-spacing': 'off',
    'style/yield-star-spacing': 'off',
    'style/function-call-spacing': 'off',
    'style/template-tag-spacing': 'off',
    'style/no-whitespace-before-property': 'off',
    'style/no-mixed-operators': 'off',
    'style/indent-binary-ops': 'off',
    'ts/type-generic-spacing': 'off',
    'ts/type-named-tuple-spacing': 'off',
    // Markdown rules
    'markdown/heading-increment': 'warn',
    'markdown/heading-style': 'warn',
    'markdown/no-missing-space-atx': 'error',
    'markdown/no-multiple-space-atx': 'error',
    'markdown/no-missing-space-closed-atx': 'error',
    'markdown/no-multiple-space-closed-atx': 'error',
    'markdown/blanks-around-headings': 'warn',
    'markdown/heading-start-left': 'warn',
    'markdown/no-duplicate-heading': 'warn',
    'markdown/single-title': 'warn',
    'markdown/no-trailing-punctuation': 'warn',
    'markdown/ul-style': 'warn',
    'markdown/list-indent': 'error',
    'markdown/ul-indent': 'warn',
    'markdown/ol-prefix': 'warn',
    'markdown/list-marker-space': 'error',
    'markdown/blanks-around-lists': 'warn',
    'markdown/no-trailing-spaces': 'error',
    'markdown/no-hard-tabs': 'error',
    'markdown/no-multiple-blanks': 'warn',
    'markdown/no-multiple-space-blockquote': 'error',
    'markdown/no-blanks-blockquote': 'warn',
    'markdown/blanks-around-fences': 'warn',
    'markdown/single-trailing-newline': 'error',
    'markdown/blanks-around-tables': 'warn',
    'markdown/no-reversed-links': 'error',
    'markdown/no-bare-urls': 'warn',
    'markdown/no-space-in-links': 'error',
    'markdown/no-empty-links': 'error',
    'markdown/link-fragments': 'warn',
    'markdown/reference-links-images': 'warn',
    'markdown/link-image-reference-definitions': 'warn',
    'markdown/link-image-style': 'warn',
    'markdown/descriptive-link-text': 'warn',
    'markdown/line-length': 'off',
    'markdown/commands-show-output': 'warn',
    'markdown/fenced-code-language': 'warn',
    'markdown/code-block-style': 'warn',
    'markdown/code-fence-style': 'warn',
    'markdown/no-emphasis-as-heading': 'warn',
    'markdown/no-space-in-emphasis': 'warn',
    'markdown/no-space-in-code': 'warn',
    'markdown/emphasis-style': 'warn',
    'markdown/strong-style': 'warn',
    'markdown/no-inline-html': 'warn',
    'markdown/hr-style': 'warn',
    'markdown/first-line-heading': 'off',
    'markdown/required-headings': 'off',
    'markdown/proper-names': 'off',
    'markdown/no-alt-text': 'warn',
    'markdown/table-pipe-style': 'warn',
    'markdown/table-column-count': 'error',
    'markdown/table-column-style': 'warn',
    // Lockfile security rules
    'lockfile/validate-host': ['warn', { allowedHosts: ['npm', 'yarn'] }],
    'lockfile/validate-https': 'error',
    'lockfile/validate-integrity': ['warn', { requiredAlgorithm: 'sha512' }],
    'lockfile/validate-package-names': 'error',
    'lockfile/validate-scheme': ['error', { allowedSchemes: ['https:', 'git+https:', 'git+ssh:'] }],
  },
  verbose: true,
}

// Lazy-loaded config to avoid top-level await (enables bun --compile)
let _config: PickierConfig | null = null

export async function getConfig(): Promise<PickierConfig> {
  if (!_config) {
    _config = await loadConfig({
      name: 'pickier',
      defaultConfig,
    })
  }
  return _config
}

// For backwards compatibility - synchronous access with default fallback
export const config: PickierConfig = defaultConfig
